2021-05-21 13:34:27,331 ERROR [n-b36418e24d2.a-b35fc290bb8.ServerMetaBean] - Failed to log game results to file
java.nio.file.NoSuchFileException: logs/game_210521-133427_1961157731.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
	at java.base/java.nio.file.Files.write(Files.java:3556)
	at java.base/java.nio.file.Files.write(Files.java:3607)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.logGameResults(ServerBean.java:455)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.execute(ServerBean.java:375)
	at de.dailab.jiactng.agentcore.execution.BasicExecutionCycle$1.run(BasicExecutionCycle.java:79)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-21 13:34:28,033 ERROR [n-b36418e24d2.a-b35fc290bb8.ServerMetaBean] - Failure when handling message [Headers: {JiacTNGSenderAddress=>msgbox:n-b36e36ec6f2/a-b36fd09a67b;JiacTNGSendToAddress=>n-b36418e24d2/a-b35fc290bb8}, Payload: WorkerMessage(game=1961157731, worker=w2, action=NORTH), Sender: msgbox:n-b36e36ec6f2/a-b36fd09a67b]
java.lang.IllegalArgumentException: No value found for key 1961157731
	at de.dailab.jiactng.aot.gridworld.util.ThrowMap.get(ThrowMap.java:28)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.handleMessage(ServerBean.java:221)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean$MessageObserver.notify(ServerBean.java:484)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.notify(EventedSpaceWrapper.java:183)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.fire(EventedSpaceWrapper.java:146)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.run(EventedSpaceWrapper.java:117)
2021-05-21 13:34:29,033 ERROR [n-b36418e24d2.a-b35fc290bb8.ServerMetaBean] - Failure when handling message [Headers: {JiacTNGSenderAddress=>msgbox:n-b36e36ec6f2/a-b36fd09a67b;JiacTNGSendToAddress=>n-b36418e24d2/a-b35fc290bb8}, Payload: WorkerMessage(game=1961157731, worker=w2, action=NORTH), Sender: msgbox:n-b36e36ec6f2/a-b36fd09a67b]
java.lang.IllegalArgumentException: No value found for key 1961157731
	at de.dailab.jiactng.aot.gridworld.util.ThrowMap.get(ThrowMap.java:28)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.handleMessage(ServerBean.java:221)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean$MessageObserver.notify(ServerBean.java:484)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.notify(EventedSpaceWrapper.java:183)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.fire(EventedSpaceWrapper.java:146)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.run(EventedSpaceWrapper.java:117)
2021-05-21 13:34:30,043 ERROR [n-b36418e24d2.a-b35fc290bb8.ServerMetaBean] - Failure when handling message [Headers: {JiacTNGSenderAddress=>msgbox:n-b36e36ec6f2/a-b36fd09a67b;JiacTNGSendToAddress=>n-b36418e24d2/a-b35fc290bb8}, Payload: WorkerMessage(game=1961157731, worker=w2, action=NORTH), Sender: msgbox:n-b36e36ec6f2/a-b36fd09a67b]
java.lang.IllegalArgumentException: No value found for key 1961157731
	at de.dailab.jiactng.aot.gridworld.util.ThrowMap.get(ThrowMap.java:28)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean.handleMessage(ServerBean.java:221)
	at de.dailab.jiactng.aot.gridworld.server.ServerBean$MessageObserver.notify(ServerBean.java:484)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.notify(EventedSpaceWrapper.java:183)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.fire(EventedSpaceWrapper.java:146)
	at org.sercho.masp.space.event.EventedSpaceWrapper$EventDispatcher.run(EventedSpaceWrapper.java:117)
2021-05-21 13:34:30,476 ERROR [org.apache.activemq.thread.TaskRunnerFactory] - Error in thread 'ActiveMQ VMTransport: vm://n-b36418e24d2StandardJMSBroker#1-1'
org.apache.activemq.broker.BrokerStoppedException: Broker BrokerService[n-b36418e24d2StandardJMSBroker] is being stopped
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:193)
	at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
	at org.apache.activemq.transport.vm.VMTransport.iterate(VMTransport.java:270)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-21 13:34:30,481 WARN [org.apache.activemq.broker.TransportConnection.Transport] - Transport Connection to: vm://n-b36418e24d2StandardJMSBroker#4 failed: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://n-b36418e24d2StandardJMSBroker#4) stopped.
2021-05-21 13:34:30,484 ERROR [org.apache.activemq.broker.TransportConnector] - Could not accept connection : java.lang.InterruptedException
2021-05-21 13:34:30,491 ERROR [n-b36418e24d2.IDirectory.jms] - Sending of Message to address 'group:df@dfgroup' through JMS failed!
javax.jms.JMSException: peer (vm://n-b36418e24d2StandardJMSBroker#1) stopped.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1398)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1324)
	at org.apache.activemq.ActiveMQSession.send(ActiveMQSession.java:1971)
	at org.apache.activemq.ActiveMQMessageProducer.send(ActiveMQMessageProducer.java:288)
	at org.apache.activemq.ActiveMQMessageProducer.send(ActiveMQMessageProducer.java:223)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSSender.sendMessage(JMSSender.java:52)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSSender.send(JMSSender.java:43)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSMessageTransport.send(JMSMessageTransport.java:215)
	at de.dailab.jiactng.agentcore.directory.DirectoryAgentNodeBean.sendMessage(DirectoryAgentNodeBean.java:1472)
	at de.dailab.jiactng.agentcore.directory.DirectoryAgentNodeBean.doStop(DirectoryAgentNodeBean.java:295)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.stop(AbstractLifecycle.java:181)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.doStop(SimpleAgentNode.java:978)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.stop(AbstractLifecycle.java:181)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.shutdown(SimpleAgentNode.java:819)
	at de.dailab.jiactng.agentcore.SimpleAgentNode$1.run(SimpleAgentNode.java:144)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://n-b36418e24d2StandardJMSBroker#1) stopped.
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:229)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.broker.TransportConnection.doStop(TransportConnection.java:1164)
	at org.apache.activemq.broker.TransportConnection$4.run(TransportConnection.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-21 13:34:30,492 ERROR [n-b36418e24d2.IDirectory] - sendMessage failed. Message:
[Headers: {JiacTNGSenderAddress=>msgbox:df@n-b36418e24d2;JiacTNGProtocolID=>df:bye;JiacTNGGroupAddress=>df@dfgroup;UUID=>n-b36418e24d2}, Payload: null, Sender: msgbox:df@n-b36418e24d2]
de.dailab.jiactng.agentcore.comm.CommunicationException: error while sending message
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSMessageTransport.send(JMSMessageTransport.java:221)
	at de.dailab.jiactng.agentcore.directory.DirectoryAgentNodeBean.sendMessage(DirectoryAgentNodeBean.java:1472)
	at de.dailab.jiactng.agentcore.directory.DirectoryAgentNodeBean.doStop(DirectoryAgentNodeBean.java:295)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.stop(AbstractLifecycle.java:181)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.doStop(SimpleAgentNode.java:978)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.stop(AbstractLifecycle.java:181)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.shutdown(SimpleAgentNode.java:819)
	at de.dailab.jiactng.agentcore.SimpleAgentNode$1.run(SimpleAgentNode.java:144)
Caused by: javax.jms.JMSException: peer (vm://n-b36418e24d2StandardJMSBroker#1) stopped.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1398)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1324)
	at org.apache.activemq.ActiveMQSession.send(ActiveMQSession.java:1971)
	at org.apache.activemq.ActiveMQMessageProducer.send(ActiveMQMessageProducer.java:288)
	at org.apache.activemq.ActiveMQMessageProducer.send(ActiveMQMessageProducer.java:223)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSSender.sendMessage(JMSSender.java:52)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSSender.send(JMSSender.java:43)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSMessageTransport.send(JMSMessageTransport.java:215)
	... 7 more
Caused by: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://n-b36418e24d2StandardJMSBroker#1) stopped.
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:229)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.broker.TransportConnection.doStop(TransportConnection.java:1164)
	at org.apache.activemq.broker.TransportConnection$4.run(TransportConnection.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-21 13:34:30,496 WARN [n-b36418e24d2.a-b35fc290bb8.CommunicationBean.jms] - could not close connection 
javax.jms.JMSException: peer (vm://n-b36418e24d2StandardJMSBroker#3) stopped.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.doSyncSendPacket(ActiveMQConnection.java:1450)
	at org.apache.activemq.ActiveMQConnection.close(ActiveMQConnection.java:687)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSMessageTransport.doCleanup(JMSMessageTransport.java:110)
	at de.dailab.jiactng.agentcore.comm.CommunicationBean.doCleanup(CommunicationBean.java:172)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.cleanup(AbstractLifecycle.java:221)
	at de.dailab.jiactng.agentcore.Agent.doCleanup(Agent.java:370)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.cleanup(AbstractLifecycle.java:221)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.doCleanup(SimpleAgentNode.java:996)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.cleanup(AbstractLifecycle.java:221)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.shutdown(SimpleAgentNode.java:820)
	at de.dailab.jiactng.agentcore.SimpleAgentNode$1.run(SimpleAgentNode.java:144)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://n-b36418e24d2StandardJMSBroker#3) stopped.
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:229)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.broker.TransportConnection.doStop(TransportConnection.java:1164)
	at org.apache.activemq.broker.TransportConnection$4.run(TransportConnection.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-21 13:34:30,499 WARN [n-b36418e24d2.IDirectory.jms] - could not stop JMS connection 
org.apache.activemq.ConnectionFailedException: The JMS connection has failed: peer (vm://n-b36418e24d2StandardJMSBroker#1) stopped.
	at org.apache.activemq.ActiveMQConnection.checkClosedOrFailed(ActiveMQConnection.java:1471)
	at org.apache.activemq.ActiveMQConnection.doStop(ActiveMQConnection.java:575)
	at org.apache.activemq.ActiveMQConnection.stop(ActiveMQConnection.java:564)
	at de.dailab.jiactng.agentcore.comm.transport.jms.JMSMessageTransport.doCleanup(JMSMessageTransport.java:103)
	at de.dailab.jiactng.agentcore.directory.DirectoryAgentNodeBean.doCleanup(DirectoryAgentNodeBean.java:311)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.cleanup(AbstractLifecycle.java:221)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.doCleanup(SimpleAgentNode.java:1011)
	at de.dailab.jiactng.agentcore.lifecycle.AbstractLifecycle.cleanup(AbstractLifecycle.java:221)
	at de.dailab.jiactng.agentcore.SimpleAgentNode.shutdown(SimpleAgentNode.java:820)
	at de.dailab.jiactng.agentcore.SimpleAgentNode$1.run(SimpleAgentNode.java:144)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://n-b36418e24d2StandardJMSBroker#1) stopped.
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:229)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:65)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.broker.TransportConnection.doStop(TransportConnection.java:1164)
	at org.apache.activemq.broker.TransportConnection$4.run(TransportConnection.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
